use cbindgen::*;

const WARNING: &str = r#"// Warning, this file is autogenerated by cbindgen.
// Don't modify this manually."#;

fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let crate_name = std::env::var("CARGO_PKG_NAME").unwrap();

    Builder::new()
        .with_crate(crate_dir)
        .with_config(cbindgen_config(&crate_name))
        .generate()
        .expect("Unable to generate C bindings")
        .write_to_file(format!("target/include/{crate_name}.h"));
}

fn cbindgen_config(crate_name: &str) -> Config {
    Config {
        language: Language::C,
        include_guard: Some(crate_name.to_uppercase()),
        autogen_warning: Some(WARNING.to_string()),
        include_version: true,
        braces: Braces::SameLine,
        line_length: 120,
        tab_width: 2,
        documentation: true,
        documentation_style: DocumentationStyle::Doxy,
        documentation_length: DocumentationLength::Full,
        style: Style::Both,
        ..Default::default()
    }
}
